# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-tFojM9FJXZoipv0na7HLnvyrG7K-u1O
"""

a=45
b=24
c=a+b
print(c)